name: Check bHaptics builds

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - docs/**
      - '**/*.md'
  push:
    branches:
      - master
    paths-ignore:
      - docs/**
      - '**/*.md'

jobs:
  check-build-os:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        target:
          - bhaptics_tactsuit_x16
          - bhaptics_tactsuit_x16_pca9685
          - bhaptics_tactsuit_x40
          - bhaptics_tactosy2_forearm_left
          - bhaptics_tactosy2_forearm_right
          - bhaptics_tactosyh_hand_left
          - bhaptics_tactosyh_hand_right
          - bhaptics_tactosyf_foot_left
          - bhaptics_tactosyf_foot_right
          - bhaptics_tactal
          - bhaptics_tactot_dk3

    steps:
      - uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-pio-${{ hashFiles('**/lockfiles') }}
          restore-keys: |
            ${{ runner.os }}-pio-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          pio upgrade --dev
          pio pkg update --global

      - name: Build
        run: |
          echo "::group::platformio.ini"
          cat platformio.ini
          echo "::endgroup::"
          pio run --environment ${{matrix.target}}

  build-flags:
    needs: check-build-os
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        target:
          - bhaptics_tactsuit_x16
          - bhaptics_tactsuit_x16_pca9685
          - bhaptics_tactsuit_x40
          - bhaptics_tactosy2_forearm_right
          - bhaptics_tactosyh_hand_right
          - bhaptics_tactosyf_foot_right
          - bhaptics_tactal
          - bhaptics_tactot_dk3
        ble:
          - "-D BLUETOOTH_USE_NIMBLE=true"
          - "-D BLUETOOTH_USE_NIMBLE=false"

    steps:
      - uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-pio-${{ hashFiles('**/lockfiles') }}
          restore-keys: |
            ${{ runner.os }}-pio-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Update build flags (non-macOS)
        if: runner.os != 'macOS'
        run: |
          sed -i '/__OH_FIRMWARE__/p; s/__OH_FIRMWARE__/BLUETOOTH_USE_NIMBLE=false/' platformio.ini

      - name: Update build flags (macOS)
        if: runner.os == 'macOS'
        run: |
          sed -i '' '/__OH_FIRMWARE__/p; s/__OH_FIRMWARE__/BLUETOOTH_USE_NIMBLE=false/' platformio.ini

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          pio upgrade --dev
          pio pkg update --global

      - name: Build
        run: |
          echo "::group::platformio.ini"
          cat platformio.ini
          echo "::endgroup::"
          pio run --environment ${{matrix.target}}